(* fixtures.sml -- GENERATED by bin/gen_fixtures.py. Do not edit.
   Authoritative PNG fixtures built with python's zlib; the image is a
   known 3x2 RGBA raster. *)

structure Fixtures =
struct
  fun bytes l = Word8Vector.fromList l
  val width = 3
  val height = 2

  (* expected RGBA8 data (flat) for the full-color decode *)
  val expected = bytes [0wx0A,0wx14,0wx1E,0wxFF,0wx28,0wx32,0wx3C,0wxFF,0wx46,0wx50,0wx5A,0wxFF,0wx64,0wx6E,0wx78,0wxC8,0wx82,0wx8C,0wx96,0wx80,0wxA0,0wxAA,0wxB4,0wx40]

  (* expected when alpha is forced opaque (RGB / grayscale-noalpha) *)
  val expected_opaque = bytes [0wx0A,0wx14,0wx1E,0wxFF,0wx28,0wx32,0wx3C,0wxFF,0wx46,0wx50,0wx5A,0wxFF,0wx64,0wx6E,0wx78,0wxFF,0wx82,0wx8C,0wx96,0wxFF,0wxA0,0wxAA,0wxB4,0wxFF]

  (* expected grayscale expansion with original alpha (color type 4) *)
  val expected_gray = bytes [0wx0A,0wx0A,0wx0A,0wxFF,0wx28,0wx28,0wx28,0wxFF,0wx46,0wx46,0wx46,0wxFF,0wx64,0wx64,0wx64,0wxC8,0wx82,0wx82,0wx82,0wx80,0wxA0,0wxA0,0wxA0,0wx40]

  (* expected grayscale expansion, alpha forced opaque (color type 0) *)
  val expected_gray0 = bytes [0wx0A,0wx0A,0wx0A,0wxFF,0wx28,0wx28,0wx28,0wxFF,0wx46,0wx46,0wx46,0wxFF,0wx64,0wx64,0wx64,0wxFF,0wx82,0wx82,0wx82,0wxFF,0wxA0,0wxA0,0wxA0,0wxFF]

  val png_rgba_none = bytes [0wx89,0wx50,0wx4E,0wx47,0wx0D,0wx0A,0wx1A,0wx0A,0wx00,0wx00,0wx00,0wx0D,0wx49,0wx48,0wx44,0wx52,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00,0wx02,0wx08,0wx06,0wx00,0wx00,0wx00,0wx9D,0wx74,0wx66,0wx1A,0wx00,0wx00,0wx00,0wx23,0wx49,0wx44,0wx41,0wx54,0wx78,0wxDA,0wx63,0wxE0,0wx12,0wx91,0wxFB,0wxAF,0wx61,0wx64,0wxF3,0wxDF,0wx2D,0wx20,0wxEA,0wx3F,0wx43,0wx4A,0wx5E,0wxC5,0wx89,0wxA6,0wx9E,0wx69,0wx0D,0wx0B,0wx56,0wx6D,0wx71,0wx00,0wx00,0wx7F,0wx30,0wx0B,0wx34,0wx7D,0wx7E,0wxB9,0wx29,0wx00,0wx00,0wx00,0wx00,0wx49,0wx45,0wx4E,0wx44,0wxAE,0wx42,0wx60,0wx82]
  val png_rgba_sub = bytes [0wx89,0wx50,0wx4E,0wx47,0wx0D,0wx0A,0wx1A,0wx0A,0wx00,0wx00,0wx00,0wx0D,0wx49,0wx48,0wx44,0wx52,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00,0wx02,0wx08,0wx06,0wx00,0wx00,0wx00,0wx9D,0wx74,0wx66,0wx1A,0wx00,0wx00,0wx00,0wx1D,0wx49,0wx44,0wx41,0wx54,0wx78,0wxDA,0wx63,0wxE4,0wx12,0wx91,0wxFB,0wx2F,0wx27,0wx27,0wxC7,0wx00,0wxC2,0wx8C,0wx29,0wx79,0wx15,0wx27,0wx80,0wx8C,0wx1D,0wx40,0wx7C,0wx00,0wx00,0wx45,0wx5D,0wx06,0wx30,0wxCE,0wx6B,0wxB3,0wx4E,0wx00,0wx00,0wx00,0wx00,0wx49,0wx45,0wx4E,0wx44,0wxAE,0wx42,0wx60,0wx82]
  val png_rgba_up = bytes [0wx89,0wx50,0wx4E,0wx47,0wx0D,0wx0A,0wx1A,0wx0A,0wx00,0wx00,0wx00,0wx0D,0wx49,0wx48,0wx44,0wx52,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00,0wx02,0wx08,0wx06,0wx00,0wx00,0wx00,0wx9D,0wx74,0wx66,0wx1A,0wx00,0wx00,0wx00,0wx1F,0wx49,0wx44,0wx41,0wx54,0wx78,0wxDA,0wx63,0wxE2,0wx12,0wx91,0wxFB,0wxAF,0wx61,0wx64,0wxF3,0wxDF,0wx2D,0wx20,0wxEA,0wx3F,0wx53,0wx54,0wx54,0wxD4,0wx49,0wx20,0wx6E,0wx04,0wx62,0wx47,0wx00,0wx76,0wx4B,0wx09,0wx79,0wxDE,0wxAB,0wxD2,0wx67,0wx00,0wx00,0wx00,0wx00,0wx49,0wx45,0wx4E,0wx44,0wxAE,0wx42,0wx60,0wx82]
  val png_rgba_avg = bytes [0wx89,0wx50,0wx4E,0wx47,0wx0D,0wx0A,0wx1A,0wx0A,0wx00,0wx00,0wx00,0wx0D,0wx49,0wx48,0wx44,0wx52,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00,0wx02,0wx08,0wx06,0wx00,0wx00,0wx00,0wx9D,0wx74,0wx66,0wx1A,0wx00,0wx00,0wx00,0wx20,0wx49,0wx44,0wx41,0wx54,0wx78,0wxDA,0wx63,0wxE6,0wx12,0wx91,0wxFB,0wxAF,0wxAC,0wxA1,0wxDB,0wx60,0wx64,0wx6E,0wxD3,0wxC0,0wx1C,0wx9F,0wx92,0wxE9,0wx69,0wx63,0wx63,0wx33,0wx17,0wx88,0wx1B,0wx01,0wx59,0wxA6,0wx07,0wx5A,0wx00,0wx21,0wxA1,0wxAD,0wx00,0wx00,0wx00,0wx00,0wx49,0wx45,0wx4E,0wx44,0wxAE,0wx42,0wx60,0wx82]
  val png_rgba_paeth = bytes [0wx89,0wx50,0wx4E,0wx47,0wx0D,0wx0A,0wx1A,0wx0A,0wx00,0wx00,0wx00,0wx0D,0wx49,0wx48,0wx44,0wx52,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00,0wx02,0wx08,0wx06,0wx00,0wx00,0wx00,0wx9D,0wx74,0wx66,0wx1A,0wx00,0wx00,0wx00,0wx1D,0wx49,0wx44,0wx41,0wx54,0wx78,0wxDA,0wx63,0wxE1,0wx12,0wx91,0wxFB,0wx2F,0wx27,0wx27,0wxC7,0wx00,0wxC2,0wx2C,0wx51,0wx51,0wx51,0wx27,0wx81,0wx8C,0wx1D,0wx40,0wx7C,0wx00,0wx00,0wx43,0wx5B,0wx05,0wxFB,0wxC5,0wx0F,0wx2A,0wx23,0wx00,0wx00,0wx00,0wx00,0wx49,0wx45,0wx4E,0wx44,0wxAE,0wx42,0wx60,0wx82]

  val png_rgb   = bytes [0wx89,0wx50,0wx4E,0wx47,0wx0D,0wx0A,0wx1A,0wx0A,0wx00,0wx00,0wx00,0wx0D,0wx49,0wx48,0wx44,0wx52,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00,0wx02,0wx08,0wx02,0wx00,0wx00,0wx00,0wx12,0wx16,0wxF1,0wx4D,0wx00,0wx00,0wx00,0wx1C,0wx49,0wx44,0wx41,0wx54,0wx78,0wxDA,0wx63,0wxE0,0wx12,0wx91,0wxD3,0wx30,0wxB2,0wx71,0wx0B,0wx88,0wx62,0wx48,0wxC9,0wxAB,0wx68,0wxEA,0wx99,0wxB6,0wx60,0wxD5,0wx16,0wx00,0wx2E,0wx5E,0wx06,0wxAF,0wx49,0wxB8,0wx0A,0wx41,0wx00,0wx00,0wx00,0wx00,0wx49,0wx45,0wx4E,0wx44,0wxAE,0wx42,0wx60,0wx82]
  val png_gray  = bytes [0wx89,0wx50,0wx4E,0wx47,0wx0D,0wx0A,0wx1A,0wx0A,0wx00,0wx00,0wx00,0wx0D,0wx49,0wx48,0wx44,0wx52,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00,0wx02,0wx08,0wx00,0wx00,0wx00,0wx00,0wxB8,0wx1F,0wx39,0wxC6,0wx00,0wx00,0wx00,0wx10,0wx49,0wx44,0wx41,0wx54,0wx78,0wxDA,0wx63,0wxE4,0wx92,0wx93,0wx63,0wx4C,0wx91,0wx93,0wx03,0wx00,0wx03,0wx2A,0wx00,0wxE9,0wx18,0wx89,0wx08,0wx54,0wx00,0wx00,0wx00,0wx00,0wx49,0wx45,0wx4E,0wx44,0wxAE,0wx42,0wx60,0wx82]
  val png_gray_alpha = bytes [0wx89,0wx50,0wx4E,0wx47,0wx0D,0wx0A,0wx1A,0wx0A,0wx00,0wx00,0wx00,0wx0D,0wx49,0wx48,0wx44,0wx52,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00,0wx02,0wx08,0wx04,0wx00,0wx00,0wx00,0wx37,0wx7D,0wxAE,0wx91,0wx00,0wx00,0wx00,0wx16,0wx49,0wx44,0wx41,0wx54,0wx78,0wxDA,0wx63,0wxE1,0wxFA,0wx2F,0wxC7,0wx20,0wxC7,0wxC0,0wx12,0wx75,0wx52,0wx6E,0wx87,0wxDC,0wx01,0wx00,0wx18,0wxD5,0wx04,0wx25,0wx2B,0wx10,0wx09,0wx9B,0wx00,0wx00,0wx00,0wx00,0wx49,0wx45,0wx4E,0wx44,0wxAE,0wx42,0wx60,0wx82]
end
